parameters:
    locale: 'en'
    app.name: Shopker
    app.version: '4.1.6'
    app.web_dir_path: '%kernel.root_dir%/../../public'
    app.files_dir_path: '%app.web_dir_path%/uploads'
    app.locale_list: ''
    app.logo_image_url: /img/shk-logo-small-blue.png
    app.files_dir_url: /uploads
    app.template_theme: default
    app.files_ext_blacklist:
        - php
        - php3
        - php4
        - php5
        - pl
        - cgi
    app.editable_css:
        - /custom.css
    app.editable_js:
        - /app.js
        - /shopkeeper.js
    app.editable_config:
        - /packages/omnipay.yaml
        - /packages/liip_imagine.yaml
        - /resources/admin_menu.yaml
        - /resources/forms/contacts.yaml
    app.file_manager_enabled: true
    mongodb_server: 127.0.0.1
    mongodb_port: 27017
    mongodb_user: ''
    mongodb_password: ''
    mongodb_database: ''
    mongodb_uri: 'mongodb://127.0.0.1:27017'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: '465'
    mailer_user: ''
    mailer_password: ''
    mailer_encryption: 'ssl'
    mailer_auth_mode: 'login'
